[theme]
# Primary accent color for interactive elements.
primaryColor = "#0d1114"

# Background color for the main content area.
backgroundColor = "#0d1114"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#012330"

# Color used for almost all text.
textColor = "#FFF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"